package com.sensitiveinfo

internal object AppConstants {
  const val DIALOG_FRAGMENT_TAG = "authFragment"

  // Error codes
  const val KM_ERROR_KEY_USER_NOT_AUTHENTICATED = "KM_ERROR_KEY_USER_NOT_AUTHENTICATED"
  const val FINGERPRINT_AUTHENTICATION_HELP = "FINGERPRINT_AUTHENTICATION_HELP"
  const val E_AUTHENTICATION_NOT_RECOGNIZED = "E_AUTHENTICATION_NOT_RECOGNIZED"
  const val E_AUTHENTICATION_CANCELLED = "E_AUTHENTICATION_CANCELLED"
  const val E_BIOMETRIC_NOT_SUPPORTED = "E_BIOMETRIC_NOT_SUPPORTED"
  const val E_INIT_FAILURE = "E_INIT_FAILURE"
  const val E_BIOMETRICS_INVALIDATED = "E_BIOMETRICS_INVALIDATED"
}
