package br.com.classapp.RNSensitiveInfo.utils;

public interface AppConstants {

    String DIALOG_FRAGMENT_TAG = "authFragment";

    // error codes
    String E_BIOMETRIC_NOT_SUPPORTED = "E_BIOMETRIC_NOT_SUPPORTED";
    String FINGERPRINT_AUTHENTICATION_HELP = "FINGERPRINT_AUTHENTICATION_HELP";
    String E_AUTHENTICATION_NOT_RECOGNIZED = "E_AUTHENTICATION_NOT_RECOGNIZED";
    String E_AUTHENTICATION_CANCELLED = "E_AUTHENTICATION_CANCELLED";
    String E_INIT_FAILURE = "E_INIT_FAILURE";
}